name = "%worker_name%"
main = "_worker.js"
compatibility_date = "2023-05-26"
routes = [
  { pattern = "ava.game.naver.com.%subdomain_name%", custom_domain = true },
  { pattern = "df.game.naver.com.%subdomain_name%", custom_domain = true },
  { pattern = "help.viu.com.%subdomain_name%", custom_domain = true },
  { pattern = "zaintest.vuclip.com.%subdomain_name%", custom_domain = true },
  { pattern = "quiz.int.vidio.com.%subdomain_name%", custom_domain = true },
  { pattern = "img.email1.vidio.com.%subdomain_name%", custom_domain = true },
  { pattern = "data.mt.%subdomain_name%", custom_domain = true },
  { pattern = "bimbel.ruangguru.com.%subdomain_name%", custom_domain = true },
  { pattern = "zoomgov.com.%subdomain_name%", custom_domain = true },
  { pattern = "support.zoom.us.%subdomain_name%", custom_domain = true },
  { pattern = "telkomuniversity.ac.id.%subdomain_name%", custom_domain = true },
  { pattern = "npca.netflix.com.%subdomain_name%", custom_domain = true },
  { pattern = "cache.netflix.com.%subdomain_name%", custom_domain = true },
  { pattern = "investor.fb.com.%subdomain_name%", custom_domain = true },
  { pattern = "investor.spotify.com.%subdomain_name%", custom_domain = true },
  { pattern = "bonesignal.com.%subdomain_name%", custom_domain = true }

]
workers_dev = false
[vars]
UUID = "%uuid%"
PROXYIP = "%proxyip%"
DNS_RESOLVER_URL = "https://dns.cloudflare.com/dns-query"
